name: 'Satis build - composer repository'
description: 'Build a static composer repository using satis'

inputs:
  token:
    description: 'Token to use (ie. GITHUB_TOKEN, App token or a PAT)'
    required: true
  satis_config:
    description: 'Path to satis configuration file (default: ./satis.json)'
    required: false
    default: 'satis.json'
  package_name:
    description: 'The name of the package to add and/or update.'
    required: false

runs:
  using: "composite"
  steps:
    - env:
        COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ inputs.token }}"}}'
        COMPOSER_HOME: /tmp/.satis-build
      run: |
        mkdir /tmp/.satis-build
        echo "{}" > /tmp/.satis-build/composer.json

        composer g require composer/satis:dev-main --prefer-dist \
          --no-cache --no-progress --no-interaction -o \
          --ignore-platform-reqs

        if ! [ -f "${{ inputs.satis_config }}" ]; then 
          php $COMPOSER_HOME/vendor/bin/satis init ${{ inputs.satis_config }} -n \
            --name="${{ github.repository }}" \
            --homepage="https://github.com/${{ github.repository_owner }}"
        fi

        if [ -n "${{ inputs.package_name }}"]; then
          php $COMPOSER_HOME/vendor/bin/satis add -n --name=${PACKAGE} "https://github.com/${PACKAGE}" ${SATIS_CONFIG} || true
          php $COMPOSER_HOME/vendor/bin/satis build -n ${SATIS_CONFIG} . ${PACKAGE}
        else
          php $COMPOSER_HOME/vendor/bin/satis build -n ${SATIS_CONFIG}
        fi

        if cat ${{ inputs.satis_config }} | jq .archive -e; then
          php $COMPOSER_HOME/vendor/bin/satis purge ${{ inputs.satis_config }} -n
        fi

      shell: bash
    - run: |
        rm -rf $COMPOSER_HOME
      shell: bash

branding:
  icon: 'download-cloud'
  color: 'gray-dark'
